### ISSUE TITLE
BuyLimit with "ConditionType"

### ISSUE THREAD

**Issue by trojanhost** [pepijnolivier/laravel-bittrex#1]
i use bittrex API 1.1 and 2.0 for trading client (Delphi).
how use method BuyLimit with "ConditionType" and "Target" parameters?

this sample dont work? :

https://bittrex.com/api/v2.0/auth/market/tradebuy?&nonce=1502481723&MarketName=BTC-BCC&OrderType=LIMIT&Quantity=0.0005&Rate=0.10271362101&TimeInEffect=IMMEDIATE_OR_CANCEL&ConditionType=GREATER_THAN&Target=0.10271362101&__RequestVerificationToken=********

**Comment by pepijnolivier** [comment]
@trojanhost the 2.0 API is undocumented, and prone to change.
I personally wouldn't trade using that API.


The API docs for the official API (v1.1) are over at https://bittrex.com/home/api
You should refer to this endpoint: `/market/buylimit`

And here is [my implementation](https://github.com/pepijnolivier/laravel-bittrex/blob/master/src/Client.php#L186).

Hope this helps.

**Comment by pepijnolivier** [comment]
By the way, for further questions on your personal project, you should head over to the bittrex slack group ! There's an api-developers channel

https://bittrex.slack.com

Join here: http://slack.bittrex.com/
